


model:
    backbone:
        module: "DINOv2"
        params:
            model_name: "vits"

    depther:
        module: "DADepther"
        params: {}

    
    neck: 
        module: "build_composed_neck"
        params:
            config_filepath: "/home/qinguoqing/project/WDM3D/config/neck/neck.yaml"

    detector_2d:
        module: "DetectionModel"
        params:
            cfg: "/home/qinguoqing/project/WDM3D/config/yolo/yolov9-t.yaml"

    

    head:
        module: "WDM3DPredictorHead"
        params:
            channels: 256