


model:
    backbone:
        module: "DINOv2"
        params:
            model_name: "vits"

    depther:
        module: "DADepther"
        params: {}

    
    neck: 
        base_neck:
            module: ""
        comp_neck:
            module: ""
        pe_neck:
            module: ""

    detecor_2d:
        module: "DetectionModel"
        params:
            cfg: "/home/qinguoqing/project/WDM3D/config/yolo/yolov9-t.yaml"

    

    head:
        module: ""