


model:
    backbone:
        module: "fastvit_t8"
        params:
            fork_feat: True
    
    neck: 
        base_neck:
            module: ""
        comp_neck:
            module: ""
        pe_neck:
            module: ""

    detecor_2d:
        module: "DetectionModel"
        params:
            cfg: "/home/qinguoqing/project/WDM3D/config/yolo/yolov9-t.yaml"

    

    head:
        module: ""