


dataset: "/home/qinguoqing/project/WDM3D/config/data/data.yaml"
model: "/home/qinguoqing/project/WDM3D/config/model/WDM3D.yaml"

loss:
    module: "WDM3DLoss"
    params: 
        sample_roi_points: 100
        dim_prior: [[0.8, 1.8, 0.8], [0.6, 1.8, 1.8], [1.6, 1.8, 4.]]
        loss_weights: [1, 0.9, 0.9]     # 依次为loss_3d, depth_loss, bbox2d_loss的权重
        inf_pixel_loss: 0.001
        depth_loss:
            module: "MSELoss"
            params: {}
        bbox2d_loss:
            module: "ComputeLoss"
            params: {}

optimizer:
    module: "Adam"
    params:
        lr: 0.01